replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

containerPort: 80

service:
  type: ClusterIP
  port: 80
  annotations: {}

ingress:
  enabled: false
  # nginx | traefik
  provider: nginx
  className: ""
  annotations: {}
  hosts: []
  tls: []

traefik:
  apiVersion: traefik.io/v1alpha1
  annotations: {}
  entryPoints:
    - websecure
  middlewares: []
  redirectToHTTPS: false
  tls: {}

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

podDisruptionBudget:
  enabled: false
  minAvailable: 1

# Key/value environment variables
env: {}

# Extra env entries (supports valueFrom)
extraEnv: []

# envFrom secret/configmap refs
envFrom: []

configMap:
  enabled: false
  data: {}

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

terminationGracePeriodSeconds: 30
