discriminator: "mylists-{{ target.name }}"

targets:
  - name: default
    args:
      namespace: mtvl
      domain: mtvl.example.com

args:
  - name: namespace
    default: mtvl
  - name: domain
    default: mtvl.example.com
