deployments:
  - path: mtvl
    waitReadiness: true

  - barrier: true
    message: "Waiting for backend to be created"

  - path: mtvl-frontend

commonLabels:
  app.kubernetes.io/part-of: mtvl
